services:
  postgres:
    image: postgres:17-alpine
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
  postgres-export:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    ports:
      - 9187:9187
    depends_on:
      - postgres
    environment:
      - 'DATA_SOURCE_URI=postgres:5432/mydatabase?sslmode=disable'
      - 'DATA_SOURCE_USER=myuser'
      - 'DATA_SOURCE_PASS=secret'
  prometheus:
    image: prom/prometheus:v3.0.1
    ports:
      - '9090:9090'
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - postgres-export
  grafana:
    image: grafana/grafana:11.4.2
    ports:
      - '3000:3000'
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning/datasources:ro
    depends_on:
      - prometheus